-- both test users have the password "password"

INSERT INTO users (username, password, first_name, last_name, gender, email, school_handle, is_admin, paid, competition_handle)
VALUES ('testuser',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'User',
        'male',
        'testuser@user.com',
        'tamu',
        FALSE,
        FALSE,
        NULL),
       ('testadmin',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'Admin',
        'female',
        'testadmin@user.com',
        'tamu',
        TRUE,
        TRUE,
        NULL),
        ('paiduser',
         '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
         'Paid',
         'User',
         'female',
         'paiduser@user.com',
         'tamu',
         FALSE,
         TRUE,
         'football');

INSERT INTO schools (school_handle, school_name, city, state, logo_url, facebook_url, instagram_url)
VALUES ('rice', 
        'Rice University', 
        'Houston', 
        'TX', 
        '/logos/rice-logo.png', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/'),
       ('tamu', 
        'Texas A&M University', 
        'College Station', 
        'TX', 
        '/logos/tamu-logo.png', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/'),
       ('uh', 
        'University of Houston', 
        'Houston', 
        'TX', 
        '/logos/uh-logo.png', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/'),
       ('unt', 
        'University of North Texas', 
        'Denton', 
        'TX', 
        '/logos/unt-logo.png', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/'),
       ('uta', 
        'University of Texas at Arlington', 
        'Arlington', 
        'TX', 
        '/logos/uta-logo.png', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/'),
       ('ut', 
        'University of Texas at Austin', 
        'Austin', 
        'TX', 
        '/logos/ut-logo.svg', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/'),
       ('utd', 
        'University of Texas at Dallas', 
        'Richardson', 
        'TX', 
        '/logos/utd-logo.png', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/'),
       ('utep', 
        'University of Texas at El Paso', 
        'El Paso', 
        'TX', 
        '/logos/utep-logo.png', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/'),
       ('utrgv', 
        'University of Texas, Rio Grande Valley', 
        'Edinburg', 
        'TX', 
        '/logos/utrgv-logo.png', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/'),
       ('utsa', 
        'University of Texas at San Antonio', 
        'San Antonio', 
        'TX', 
        '/logos/utsa-logo.png', 
        'https://www.facebook.com/', 
        'https://www.instagram.com/');
 
-- INSERT INTO competitions (competition, description, school_handle, username)
-- VALUES ('football', 
--         'Difficult ready trip question produce produce someone.', 
--         'tamu', 
--         'testuser'),
--        ('basketball', 
--        'To much recent it reality coach decision Mr. Dog', 
--        'tamu', 
--        'testadmin');

INSERT INTO competitions (competition_handle, competition_name, description, gender, logo_url)
VALUES ('football',
        'Football',
        'Football is a team sport played by two teams of eleven players on a rectangular field with goalposts at each end.', 
        'male', 
        '/logos/logo2.png'),
        ('soccer',
         'Soccer',
         'Soccer is a team sport played between two teams of 11 players who primarily use their feet to propel the ball around a rectangular field called a pitch.',
         'male',
         '/logos/logo2.png'),
        ('basketball',
         'Basketball',
         'Basketball is a team sport in which two teams compete with the primary objective of shooting a basketball through a hoop.',
         'male',
         '/logos/logo2.png'),
        ('basketball',
         'Basketball',
         'Basketball is a team sport in which two teams compete with the primary objective of shooting a basketball through a hoop.',
         'female',
         '/logos/logo2.png'),
        ('volleyball',
         'Volleyball',
         'Volleyball is a team sport in which two teams of six players are separated by a net.',
         'female',
         '/logos/logo2.png'),
        ('dodgeball',
         'Dodgeball',
         'Dodgeball is a team sport in which players on two teams try to throw balls and hit opponents, while avoiding being hit themselves.',
         'female',
         '/logos/logo2.png'),
        ('spokenword',
         'Spoken Word',
         'Spoken word refers to an oral poetic performance art that is based mainly on the poem as well as the aesthetic qualities.',
         null,
         '/logos/logo2.png'),
        ('writtenpoetry',
         'Written Poetry',
         'Poetry is a form of literature that uses aesthetic and often rhythmic qualities of language to evoke meanings in addition to, or in place of, a prosaic ostensible meaning.',
         null,
         '/logos/logo2.png'),
        ('photography',
         'Photography',
         'Photography is the art, application, and practice of creating durable images by recording light, either electronically by means of an image sensor, or chemically by means of a light-sensitive material such as photographic film.',
         null,
         '/logos/logo2.png'),
        ('knowledgebowl',
         'Knowledge Bowl',
         'Knowledge Bowl is the name for several interdisciplinary academic quiz bowl-like competitions across the United States and the world.',
         null,
         '/logos/logo2.png'),
        ('scrapbook',
         'Scrapbook',
         'Scrapbooking is a method of preserving, presenting and arranging personal and family history in the form of a book, box or card.',
         null,
         '/logos/logo2.png'),
       ('art',
        'Art', 
        'There is no generally agreed definition of what constitutes art, and its interpretation has varied greatly throughout history and across cultures. The three classical branches of visual art are painting, sculpture, and architecture.', 
        null, 
        '/logos/logo2.png');
